spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sysguard
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${SECRET_KEY}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true